services:
  db1:
    extends:
      file: db.yml
      service: db
    ports:
      - ${DB_PORT1:-3306}:3306
    volumes:
      - datamountain1:/var/lib/mysql

  db2:
    extends:
      file: db.yml
      service: db
    ports:
      - ${DB_PORT2:-3307}:3306
    volumes:
      - datamountain2:/var/lib/mysql
    environment:
      MARIADB_DATABASE: ${DB_NAME2}

  db3:
    extends:
      file: db.yml
      service: db
    ports:
      - ${DB_PORT3:-3308}:3306
    volumes:
      - datamountain3:/var/lib/mysql
    environment:
      MARIADB_DATABASE: ${DB_NAME2}
      MARIADB_USER: !reset null

      
volumes:
  datamountain1:
  datamountain2:
  datamountain3: