services:
  db1:
    ports:
      - ${DB_PORT1:-3306}:3306
    
  db2:
    ports:
      - ${DB_PORT2:-3307}:3306

  db3:
    environment:
      MARIADB_USER: mountain3
    ports:
      - ${DB_PORT3:-3308}:3306
      
  dbgui:
    image: phpmyadmin:${DBGUI_TAG:-latest}
    restart: always
    ports:
      - ${DBGUI_PORT:-81}:80
    environment:
      - PMA_ARBITRARY=1
